version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: spotiflyx_database
    env_file:
      - path: ./backend/.env
        required: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MDP_DB}
      MYSQL_DATABASE: ${USER_DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${MDP_DB}
    volumes:
      - spotiflyx_db_data:/var/lib/mysql
    ports:
      - "9660:9660"
    networks:
      - backend_overlay

  backend:
    build: ./backend
    container_name: spotiflyx_backend
    env_file:
      - path: ./backend/.env
        required: true
    environment:
      DATABASE_URL: mariadb://${USER_DB}:${MDP_DB}@spotiflyx_database/spotiflyx
      CRYPT_TOK: ${CRYPT_TOK}
      C_YTB_API: ${C_YTB_API}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - /home/yanisdolivet/delivery/taker_academy/spotiflyx-spotleflix/backend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - mariadb
    networks:
      - backend_overlay

  frontend:
    build: ./front/spotiflyx
    container_name: spotiflyx_frontend
    ports:
      - "8080:8080"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - backend_overlay

networks:
  backend_overlay:
    driver: bridge
    attachable: true

volumes:
  spotiflyx_db_data:
